using ZabbixApi.Common;

namespace ZabbixApi.DataModel.Alert
{
    public class Get : CommonGet
    {
        /// <summary>
        /// Return only alerts with the given IDs.
        /// </summary>
        public string[] alertids;

        /// <summary>
        /// Return only alerts generated by the given actions.
        /// </summary>
        public string[] actionids;

        /// <summary>
        /// Return only alerts generated by the given events.
        /// </summary>
        public string[] eventids;

        /// <summary>
        /// Return only alerts generated by objects from the given host groups.
        /// </summary>
        public string[] groupids;

        /// <summary>
        /// Return only alerts generated by objects from the given hosts.
        /// </summary>
        public string[] hostids;

        /// <summary>
        /// Return only message alerts that used the given media types.
        /// </summary>
        public string[] mediatypeids;

        /// <summary>
        /// Return only alerts generated by the given objects
        /// </summary>
        public string[] objectids;

        /// <summary>
        /// Return only message alerts that were sent to the given users.
        /// </summary>
        public string[] userids;

        /// <summary>
        /// 
        ///Return only alerts generated by events related to objects of the given type. Refer to the event "object" property for a list of supported object types.
        /// Default:
        /// 0 - trigger.
        /// </summary>
        public int eventobject;

        /// <summary>
        /// 
        /// Return only alerts generated by events of the given type. Refer to the event "source" property for a list of supported event types.
        /// Default:
        /// 0 - trigger events.
        /// </summary>
        public int eventsource;

        /// <summary>
        /// Return only alerts that have been generated after the given time.
        /// </summary>
        public long time_from;

        /// <summary>
        /// Return only alerts that have been generated before the given time.
        /// </summary>
        public long time_till;

        /// <summary>
        /// Return the hosts that triggered the action operation in the hosts property.
        /// </summary>
        public string selectHosts;

        /// <summary>
        /// Return the media type that was used for the message alert as an array in the mediatypes property.
        /// </summary>
        public string selectMediatypes;

        /// <summary>
        /// Return the user that the message was addressed to as an array in the users property.
        /// </summary>
        public string selectUsers;

        /// <summary>
        /// 
        /// Sort the result by the given properties.
        /// Possible values are:
        /// alertid, clock, eventid and status.
        /// </summary>
        public string[] sortfield;
    }
}