using ZabbixApi.Common;

namespace ZabbixApi.DataModel.Event
{
    public class Get : CommonGet
    {
        /// <summary>
        /// Return only events with the given IDs.
        /// </summary>
        public string[] eventids;

        /// <summary>
        /// Return only events created by objects that belong to the given host groups.
        /// </summary>
        public string[] groupids;

        /// <summary>
        /// Return only events created by objects that belong to the given hosts.
        /// </summary>
        public string[] hostids;

        /// <summary>
        /// Return only events created by the given objects.
        /// </summary>
        public int[] objectids;

        /// <summary>
        /// Return only events created by objects of the given type. Refer to the event object page for a list of supported object types. Default: 0 - trigger.
        /// </summary>
        public TypeOfObjectRelatedEvent @object;

        /// <summary>
        /// If set to true return only acknowledged events.
        /// </summary>
        public bool acknowledged;

        /// <summary>
        /// Return only events with IDs greater or equal to the given ID.
        /// </summary>
        public string eventid_from;

        /// <summary>
        /// Return only events with IDs less or equal to the given ID.
        /// </summary>
        public string eventid_till;

        /// <summary>
        /// Return only events with the given type. Refer to the event object page for a list of supported event types. 
        /// Default: 0 - trigger events.
        /// </summary>
        public TypeOfEvent source;

        /// <summary>
        /// Return only events that have been created after or at the given time.
        /// </summary>
        public long time_from;

        /// <summary>
        /// Return only events that have been created before or at the given time.
        /// </summary>
        public long time_till;

        /// <summary>
        /// Return only events with the given values.
        /// </summary>
        public string value;

        /// <summary>
        /// Return hosts containing the object that created the event in the hosts property.
        /// </summary>
        public string selectHosts;

        /// <summary>
        /// Return the object that created the event in the relatedObject property. The type of object returned depends on the event type.
        /// </summary>
        public string selectRelatedObject;

        /// <summary>
        /// Return alerts generated by the event in the alerts property. Alerts are sorted in reverse chronological order.
        /// </summary>
        public string select_alerts;

        /// <summary>
        /// Return event's acknowledges in the acknowledges property. Acknowledges are sorted in reverse chronological order.
        /// The event acknowledgement object has the following properties:
        ///  acknowledgeid - (string) acknowledgement's ID;
        ///  userid - (string) ID of the user that acknowledged the event;
        ///  eventid - (string) ID of the acknowledged event;
        ///  clock - (timestamp) time when the event was acknowledged;
        ///  message - (string) text of the acknowledgement message;
        ///  alias - (string) alias of the user that acknowledged the event;
        ///  name - (string) name of the user that acknowledged the event;
        ///  surname - (string) surname of the user that acknowledged the event. 
        /// Supports count.
        /// </summary>
        public string select_acknowledges;

        /// <summary>
        /// Sort the result by the given properties. Possible values are: eventid, objectid, clock and object (deprecated).
        /// </summary>
        public string[] sortfield;
    }
}